# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_MTK_VIBRATOR) := vibrator.o

ccflags-y += -I$(srctree)/$(src)/../mt6853
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/mt-plat
