# SPDX-License-Identifier: GPL-2.0
# camellia LOS 23: Awinic AW87xxx Smart K PA - composed module
obj-$(CONFIG_SND_SOC_AW87559) := snd-soc-aw87559.o
snd-soc-aw87559-y := aw87xxx.o aw87xxx_monitor.o aw_bin_parse.o awinic_dsp.o
